deployment:
  name: php-dynamic-qrcode
  image:
    repository: giandonatoinverso/php-dynamic-qr-code
    tag: latest
  service: 
    type: ClusterIP
    port: 80

env:
  - name: TYPE
    value: "docker"
  - name: BASE_URL
    value: "https://qr.ev.openindustry.in"
  - name: DATABASE_HOST
    value: "php-dynamic-qrcode-db-service"
  - name: DATABASE_PORT
    value: "3306"
  - name: DATABASE_NAME
    value: "qrcode"
  - name: DATABASE_USER
    value: "qrcode"
  - name: DATABASE_PASSWORD
    valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password

secret:
  name: db-credentials
  rootPassword: "rootpassword"
  password: "password"
  
statefulset:
  image:
    repository: giandonatoinverso/php-dynamic-qr-code-db
    tag: latest
  env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: root-password
    - name: MYSQL_DATABASE
      value: "qrcode"
    - name: MYSQL_USER
      value: "qrcode"
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
  service: 
    type: ClusterIP
    port: 3306
  storage: 50Mi

ingress:
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: php-dynamic-qrcode
    meta.helm.sh/release-namespace: srv-qr
  labels:
    app: srv-qr-php-dynamic-qrcode
  paths:
  - path: /
    pathType: Prefix
    backend:
      service:
        port:
          number: 80

pvc:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  storage: 50Mi
