apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deployment.name }}-ingress
  annotations:
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
  labels:
    {{ .Values.ingress.labels | toYaml | nindent 4 }}
spec:
  # ingressClassName: {{ .Values.ingress.className}}
  rules:
  - http:
      paths:
      {{- range .Values.ingress.paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Values.deployment.name }}-service
            port:
              number: {{ .backend.service.port.number }}
      {{- end }}