apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.deployment.name }}-data-pvc
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes: {{ toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
