apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  root-password: {{ .Values.secret.rootPassword | b64enc }}
  password: {{ .Values.secret.password | b64enc }}